Add openvswitch (ovs) port.
wolfSSL/osp pull request #117
Opened 2022-06-03 17:08 UTC by haydenroche5

2022-06-09 16:23 UTC, LinuxJedi requested changes
A few minor changes, but looking good.

2022-06-09 16:23 UTC, LinuxJedi commented on openvswitch/2.17.1/openvswitch-2.17.1.patch
> ++  provide commercial open source library for TLS and Crypto. Enabled using
I'd probably change this to "provide commercial and open source libraries". Can maybe say "as an alternative to" instead of "instead of".

2022-06-09 16:23 UTC, LinuxJedi commented on openvswitch/2.17.1/openvswitch-2.17.1.patch
> ++stream_ssl_set_peer_ca_cert_file__(const char *file_name)
You can probably get rid of the static declaration above as it isn't called before this implementation and the static keyword needs adding here.

2022-06-09 16:23 UTC, LinuxJedi commented on openvswitch/2.17.1/openvswitch-2.17.1.patch
> ++  WOLFSSL_URL="http://www.wolfssl.com/download.html"
https probably more appropriate for an SSL library :)

2023-07-27 13:22 UTC, JacobBarthelmeh commented
https://github.com/wolfSSL/osp/pull/149

2023-07-27 13:22 UTC, closed without merging