Secure Socket Funneling 1.1.0
wolfSSL/osp pull request #17
Opened 2018-08-02 23:00 UTC by dgarske

2018-08-09 22:54 UTC, MJSPollard submitted a review, later dismissed
All SSF unit tests passed when testing with https://github.com/wolfSSL/wolfssl/pull/1739.
I opt for this to be merged into master.

2022-04-25 21:30 UTC, ejohnstown requested changes

2022-04-25 21:30 UTC, ejohnstown commented on ssf-1.1.0/README_WOLF.md
> +    $ `cd wolfssl`
Above it says to start in the wolfSSL root directory. Do we want to change directory into the headers directory here?

2022-04-25 21:30 UTC, ejohnstown commented on ssf-1.1.0/README_WOLF.md
> +    Extracts to ssf-1.1.0
Where are we downloading and extracting this to? Into the wolfSSL root directory? It's own directory parallel to wolfSSL? Somewhere else?

2022-04-25 21:30 UTC, ejohnstown commented on ssf-1.1.0/README_WOLF.md
> +5. Download boost 1_65_1 into third_party/boost
Download where?

2022-04-25 21:30 UTC, ejohnstown commented on ssf-1.1.0/README_WOLF.md
> +    $ `wget https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz`
URL has changed. It is now found at https://boostorg.jfrog.io/artifactory/main/release/1.65.1/source/boost_1_65_1.tar.gz

2022-04-25 21:30 UTC, ejohnstown commented on ssf-1.1.0/README_WOLF.md
> +    $ `scp asio_1_65_1.tar.gz ubuntu@204.48.22.68:~/ssfwolfbuild`
When do we make ssfwolfbuild?

2022-04-25 21:30 UTC, ejohnstown commented on ssf-1.1.0/README_WOLF.md
> +    Link boost to SSF from boost_1_65_1 directory
I had to guess where to do this. I did it from the ssf directory I got unarchiving the ssf sources above.

2022-04-25 21:30 UTC, ejohnstown commented on ssf-1.1.0/README_WOLF.md
> +    $ `cd ../ssf-1.1.0`
Again which directory? Where I installed everything, boost_1_65_1 wasn't at ../..

2022-04-25 21:30 UTC, ejohnstown commented on ssf-1.1.0/README_WOLF.md
> +    $ `cmake -DCMAKE_BUILD_TYPE=Release -DWOLFSSL="/usr/local" ../`
```
CMake Error at cmake/external/ExternalPackageHelpers.cmake:246 (message):
  [Boost] # Cannot determine Boost's source directory (NOTFOUND)
Call Stack (most recent call first):
  cmake/external/ExternalPackageHelpers.cmake:818 (external_error)
  cmake/external/ExternalPackageHelpers.cmake:929 (external_search_source_path)
  cmake/external/boost/FindBoost.cmake:74 (externals_build)
  cmake/external/boost/FindBoost.cmake:256 (boost_build_components)
  CMakeLists.txt:193 (find_package)
```

2023-08-03 19:35 UTC, closed without merging

2023-08-03 19:37 UTC, dgarske commented
Note: GitHub is not letting either Jacob or I reopen this PR so I'll just open a new one with a different branch name

2023-08-03 19:42 UTC, dgarske commented
My fork was not tied upstream. Setup new proper fork. Attempting to re-open again based on that. Would like to use this PR to avoid loosing the comments.